sonar.projectKey=ISTANBULBEKLE_feza
sonar.organization=istanbulbekle

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/*.stories.tsx,**/*.module.scss.d.ts,.next/**,coverage/**,public/**,.storybook-out/**,storybook-static/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
